name: Trigger auto deployment for container-app-afgaidyiuxyhs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-afgaidyiuxyhs-AutoDeployTrigger-3e64cc21-3015-4630-aedb-4aff7707ae92.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPAFGAIDYIUXYHS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPAFGAIDYIUXYHS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPAFGAIDYIUXYHS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPAFGAIDYIUXYHS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPAFGAIDYIUXYHS_REGISTRY_PASSWORD }}
          containerAppName: container-app-afgaidyiuxyhs
          resourceGroup: appspacesragapp9acea5ad
          imageToBuild: default/container-app-afgaidyiuxyhs:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


